travis:
  secure:
    BINSTAR_TOKEN: awPO7UgMNK0RqZZ89qbmukI0sYdAGyCye/WyqU9Eo7/TMh/zt0XrB5UQbpYFe9rjWoHf08zoU/Xd/2bEVy0dmhNH1r0Uk7wOW2+Fro5y5Aqb7Fcq23fWAQ+Ol8GGVtU8DEUDh55yWVTJTwVr2ewt3rr58B1HIehylAVtdEaoVhg1LJqHCNLJ7wvfdv4T93uxc/LYhyWi9i0OazeAxEIO559wOutIHPKbQQMxA87JaAnASTFKBM/b+nNkWxZ4Pw8SuSL7cGPdTBZVIkv5uz5I5rcfPhzshQXQQrRPGWbuRjP4jISPTfb989RvLg1ohRiiBPw5pZkvO4xIcslFfL29jgXTH9CM1M9pp81nNU5gMV75gluJTw51iHuvWIM6IRC0T+fbxoAkZWkL/hTP0hUB5BL310K0G/1z4GPMrzxjT55KkGG7qRrj1bTXGyYDf1iBSlCSZYz5BXHDfpqFjfnb13O3cwtyVjJiI3XhMChiRWHxYikjYiBvWi1nv9X5CQUP6dnrY0DF7KZqX0RLSwE4N5/HMnMl5J39HU+COuefzGvaMT66ThlrmOe6hZk1XscTJAFXRC4mpjQz40hZjmjH3l76/PxWBs28ppBNKpUM0YN3eczKht3rtZ2IwQZpqAgaJE2bhzbbCmobcax1ymxpngBide4ctoQST7DMR5DmKCU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
