travis:
  secure:
    BINSTAR_TOKEN: QevB54w2aGJ1doDUvztsOpsvnPn532rt5xNJVjiiW2pGJKnXbFYxMqTdNJz43PFKpXq1qAObNXpQ6yMj25ncCpOispVRmRhIFs0zZFZ6QDYSiDEoCZyDPiPEvgtMEoDnJaTejQoOo8tyVsdbTzirgrfsRcsb7/4/+8Wap96qAuSjIJDlmCTmKx5oE03cXU9qzacOJLS9w+GyLTfATYa2LjPrXdMNa0y3nBxcIS9VBlZ7ARRw9ZHUaeQo+Zemo0JGkn1rw8EBCuwYCf7UHutHYUcAmeqGmdpRDy+qkE24H9CuCOiW95V7zKgkYfv20hvAcoGVrOyUa0hh+RN/vJcDY2XRrmF4zfHZSIhqsx52S3oHmGCqfwORZpckjklHNNBB9xNQ/UBYXIfo1u3n6hkulIzJ2nJ1cuQQRx4U+rTaAcF1jrnifEm4xmORyF47lSkD82U0W8p38bcxkbgjBAORISBYUOJjNDTdcQqjm/6w57nDomYuzZetZZQ2BGhthnoEQX3lT1mwvASgMLcH5XRVAYU9Ek4BBq61DCj8S8kK9/MUEEfMrDhYQAYUrXTMcDReBccwkjmuqcLQgxyI5R5dlDvARzQWN+omahLA+1yM+Z5JBqb6T0mI2QVOUOkRq72+DYxKIND2tmcG7mI8uFa41yH3cOvweiaNS++mTmZzg+4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
